#!/bin/sh

#Set video save path must include /
SAVE_PATH="~/storage/movies/youtube-dl/"

echo "どれをダウンロードしたいですか?"
echo
echo "1)動画"
echo "2)再生リスト"
echo "3)チャンネル"
echo "4)音声"
echo
echo "6)終了"
echo
echo "11)mkvで通常ダウンロード(最高画質を最速で)"
echo "22)通常音声ダウンロード"
echo "99)更新"
echo
read  -p " -> " SELECT
echo "${SELECT}を選択しました"

if [ "$SELECT" -eq "1" ]
then
	yt-dlp -o "$SAVE_PATH%(title)s.%(ext)s" -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" $1
elif [ "$SELECT" -eq "2" ]
then
	yt-dlp -o "$SAVE_PATH%(playlist_title)s/%(title)s.%(ext)s" -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" $1
elif [ "$SELECT" -eq "3" ]
then
	yt-dlp -o "$SAVE_PATH%(channel)s/%(title)s.%(ext)s" -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" $1
elif [ "$SELECT" -eq "4" ]
then
	echo "1)動画"
	echo "2)再生リスト"
	echo "3)終了"
	echo
	read -p " -> " SELECT1
	echo "${SELECT1}を選択しました"
	if [ "$SELECT1" -eq "1" ]
	then
		yt-dlp -x --audio-format mp3 -o "$SAVE_PATH%(title)s.%(ext)s" $1
	elif [ "$SELECT1" -eq "2" ]
	then
		yt-dlp -x --audio-format mp3 -o "$SAVE_PATH%(playlist_title)s/%(title)s.%(ext)s" $1
	elif [ "$SELECT1" -eq "3" ]
	then
		echo "終了!"
		exit
	else
		echo "やり直してください:-("
		exit
	fi
elif [ "$SELECT" -eq "6" ]
then
	echo "終了!"
	exit
elif [ "$SELECT" -eq "11" ]
then
	yt-dlp -o "$SAVE_PATH%(title)s.%(ext)s" $1
elif [ "$SELECT" -eq "22" ]
then
	yt-dlp -x -o "$SAVE_PATH%(title)s.%(ext)s" $1
elif [ "$SELECT" -eq "99" ]
then
	pip install yt-dlp -U
	sleep 3s
	exit
else
	echo "やり直してください:-("
	sleep 2s
fi

exit
