#!/bin/sh

echo
echo "termux-setup-storageを実行しますか？ (y/n) "
echo "基本的には、yを選択してください。"
read  -p " -> " SELECT

if [ $SELECT = y -o $SELECT = Y ]
then
	termux-setup-storage
else
	echo "スキップ"
fi

echo "パッケージリストを更新中..."
sleep 3s
pkg upgrade -y

echo "必要なパッケージをインストール中..."
sleep 3s
apt update && apt install -y nano curl python ffmpeg aria2

echo "yt-dlpをインストール中..."
sleep 3s
pip install -U yt-dlp

echo "termux-url-openerをダウンロード中..."
sleep 3s
mkdir ~/bin && curl https://raw.githubusercontent.com/mikutoyuto/yt-dlp-termux/main/termux-url-opener -o ~/bin/termux-url-opener && chmod +x ~/bin/termux-url-opener
echo -U >> ~/yt-dlp.conf
echo -f b >> ~/yt-dlp.conf
echo --embed-thumbnail >> ~/yt-dlp.conf
echo --embed-metadata >> ~/yt-dlp.conf
echo #--embed-chapter >> ~/yt-dlp.conf
echo --downloader aria2c >> ~/yt-dlp.conf
echo "--downloader-args aria2c:'-x16 -s16 --retry-wait=1'" >> ~/yt-dlp.conf

echo ""
echo "完成!!"
sleep 3
exit
